---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: finsight-agent
  labels:
    app: mysql-external
spec:
  selector:
    app: mysql-external
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306




