apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshiftai-data-science-cluster
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Ensure this deploys last
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: finsight-project
  source:
    repoURL: 'https://github.com/finsignt-demojam/mono-repo'
    targetRevision: main
    path: components/platform/ocpai/base
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      # Let Argo create the target namespace for MinIO.
      - CreateNamespace=false
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
