apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - broker.yaml
  - kafkasource.yaml
  - trigger.yaml
  - service.yaml
  - configure-minio-kafka-job.yaml
  - minio-credentials-secret.yaml
  - minio-credentials-secret-minio.yaml

commonLabels:
  app.kubernetes.io/part-of: finsight-platform
  app.kubernetes.io/component: eventing
