apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Ensure this deploys after any future "cluster-basics" bundles if you add them.
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: finsight-project
  source:
    repoURL: 'https://github.com/finsignt-demojam/mono-repo'
    targetRevision: main
    path: components/operators/nfd/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-nfd
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      # Let Argo create the target namespace for Node Feature Discovery Operator.
      - CreateNamespace=true
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
