apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-cluster-policy
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Ensure this deploys after any future "cluster-basics" bundles if you add them.
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: finsight-project
  source:
    repoURL: 'https://github.com/finsignt-demojam/mono-repo'
    targetRevision: main
    path: components/platform/nvidia-instance/base
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-gpu-operator
  syncPolicy:
    # Manual sync - changes require manual sync from Argo CD UI/CLI
    syncOptions:
      # Let Argo create the target namespace for NVIDIA Cluster Policy.
      - CreateNamespace=false
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5
