apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    # Ensure this deploys after any future "cluster-basics" bundles if you add them.
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: finsight-project
  source:
    repoURL: 'https://github.com/finsignt-demojam/mono-repo'
    targetRevision: main
    path: components/operators/service-mesh/base
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # openshift-operators namespace already exists, don't try to create it
      - CreateNamespace=false
      # Optional but useful in day-2:
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 5

